---
- name: Remove Nodejs
  hosts: all
  gather_facts: true
  become: true
  tasks:

    - name: remove nodejs
      apt:
        name: nodejs
        state: absent
      when: ansible_distribution == "Ubuntu"
    
    - name: purge nodejs
      apt:
        autoremove: yes
        purge: yes
      when: ansible_distribution == "Ubuntu"