---
- name: Remove Postgresql
  hosts: all
  gather_facts: true
  become: true
  tasks:
  
    - name: remove postgresql
      apt:
        name: postgresql-13
        state: absent
      when: ansible_distribution == "Ubuntu"
    
    - name: purge postgresql
      apt:
        autoremove: yes
        purge: yes
      when: ansible_distribution == "Ubuntu"